"""Add foreign key from Product to Admin

Revision ID: 6697fcadb7c9
Revises: 666badbafe8b
Create Date: 2024-07-24 19:09:54.777187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6697fcadb7c9'
down_revision = '666badbafe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
