# Use a Python base image
FROM python:3.12-slim

#Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONNUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on (default is usually 5000 for Flask)
EXPOSE 5000

# Start the application using Gunicornnnnn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
